# see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "shietomgsomuchwow"
  limiter: true  # can be disabled for a private instance
  image_proxy: true
ui:
  static_use_hash: true
  query_in_title: true
  infinite_scroll: true
  center_alignment: true
redis:
  url: redis://searxng_redis:6379/0
search:
  autocomplete: duckduckgo
